package edu.ldcollege.domain;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface LdHomeWorkFbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_home_work_fb
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ld_home_work_fb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_home_work_fb
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ld_home_work_fb (id, myid, ",
        "user_id, homework_id, ",
        "level_flag, mark)",
        "values (#{id,jdbcType=INTEGER}, #{myid,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{homeworkId,jdbcType=INTEGER}, ",
        "#{levelFlag,jdbcType=CHAR}, #{mark,jdbcType=VARCHAR})"
    })
    int insert(LdHomeWorkFb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_home_work_fb
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, myid, user_id, homework_id, level_flag, mark",
        "from ld_home_work_fb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="myid", property="myid", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="homework_id", property="homeworkId", jdbcType=JdbcType.INTEGER),
        @Result(column="level_flag", property="levelFlag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    LdHomeWorkFb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_home_work_fb
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, myid, user_id, homework_id, level_flag, mark",
        "from ld_home_work_fb"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="myid", property="myid", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="homework_id", property="homeworkId", jdbcType=JdbcType.INTEGER),
        @Result(column="level_flag", property="levelFlag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    List<LdHomeWorkFb> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_home_work_fb
     *
     * @mbg.generated
     */
    @Update({
        "update ld_home_work_fb",
        "set myid = #{myid,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "homework_id = #{homeworkId,jdbcType=INTEGER},",
          "level_flag = #{levelFlag,jdbcType=CHAR},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LdHomeWorkFb record);
}