package edu.ldcollege.domain;

public class LdHomeWorkFb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_home_work_fb.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_home_work_fb.myid
     *
     * @mbg.generated
     */
    private Integer myid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_home_work_fb.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_home_work_fb.homework_id
     *
     * @mbg.generated
     */
    private Integer homeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_home_work_fb.level_flag
     *
     * @mbg.generated
     */
    private String levelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_home_work_fb.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_home_work_fb.id
     *
     * @return the value of ld_home_work_fb.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_home_work_fb.id
     *
     * @param id the value for ld_home_work_fb.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_home_work_fb.myid
     *
     * @return the value of ld_home_work_fb.myid
     *
     * @mbg.generated
     */
    public Integer getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_home_work_fb.myid
     *
     * @param myid the value for ld_home_work_fb.myid
     *
     * @mbg.generated
     */
    public void setMyid(Integer myid) {
        this.myid = myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_home_work_fb.user_id
     *
     * @return the value of ld_home_work_fb.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_home_work_fb.user_id
     *
     * @param userId the value for ld_home_work_fb.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_home_work_fb.homework_id
     *
     * @return the value of ld_home_work_fb.homework_id
     *
     * @mbg.generated
     */
    public Integer getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_home_work_fb.homework_id
     *
     * @param homeworkId the value for ld_home_work_fb.homework_id
     *
     * @mbg.generated
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_home_work_fb.level_flag
     *
     * @return the value of ld_home_work_fb.level_flag
     *
     * @mbg.generated
     */
    public String getLevelFlag() {
        return levelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_home_work_fb.level_flag
     *
     * @param levelFlag the value for ld_home_work_fb.level_flag
     *
     * @mbg.generated
     */
    public void setLevelFlag(String levelFlag) {
        this.levelFlag = levelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_home_work_fb.mark
     *
     * @return the value of ld_home_work_fb.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_home_work_fb.mark
     *
     * @param mark the value for ld_home_work_fb.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}