package edu.ldcollege.domain;

import java.util.Date;

public class LdLesson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_lesson.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_lesson.lesession_name
     *
     * @mbg.generated
     */
    private String lesessionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_lesson.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ld_lesson.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_lesson.id
     *
     * @return the value of ld_lesson.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_lesson.id
     *
     * @param id the value for ld_lesson.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_lesson.lesession_name
     *
     * @return the value of ld_lesson.lesession_name
     *
     * @mbg.generated
     */
    public String getLesessionName() {
        return lesessionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_lesson.lesession_name
     *
     * @param lesessionName the value for ld_lesson.lesession_name
     *
     * @mbg.generated
     */
    public void setLesessionName(String lesessionName) {
        this.lesessionName = lesessionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_lesson.description
     *
     * @return the value of ld_lesson.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_lesson.description
     *
     * @param description the value for ld_lesson.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ld_lesson.created
     *
     * @return the value of ld_lesson.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ld_lesson.created
     *
     * @param created the value for ld_lesson.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }
}