package edu.ldcollege.domain;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface LdLessonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_lesson
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ld_lesson",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_lesson
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ld_lesson (id, lesession_name, ",
        "description, created)",
        "values (#{id,jdbcType=INTEGER}, #{lesessionName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{created,jdbcType=DATE})"
    })
    int insert(LdLesson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_lesson
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, lesession_name, description, created",
        "from ld_lesson",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="lesession_name", property="lesessionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.DATE)
    })
    LdLesson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_lesson
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, lesession_name, description, created",
        "from ld_lesson"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="lesession_name", property="lesessionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.DATE)
    })
    List<LdLesson> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_lesson
     *
     * @mbg.generated
     */
    @Update({
        "update ld_lesson",
        "set lesession_name = #{lesessionName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=DATE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LdLesson record);
}