package edu.ldcollege.domain;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface LdStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_student
     *
     * @mbg.generated
     */
    @Delete({
        "delete from ld_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_student
     *
     * @mbg.generated
     */
    @Insert({
        "insert into ld_student (id, name, ",
        "password)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(LdStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_student
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, password",
        "from ld_student",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    LdStudent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_student
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, password",
        "from ld_student"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    List<LdStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ld_student
     *
     * @mbg.generated
     */
    @Update({
        "update ld_student",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(LdStudent record);
}